version: "3"
services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    # you can use image or custom build below,
    # if you need CJK character with exported PDF files,
    # please change the image tag with `cjk` postfix version
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database/codimd
      - CMD_USECDN=false
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
