name: Create docker images

on: [create]

jobs:

  build:
    name: Build, push, and deploy
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: codimd
        dockerfile: deployments/Dockerfile
        registry: ghcr.io/${{ github.repository_owner	}}
        addLatest: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
